### ISSUE TITLE
Command "cognigy train" documentation needs to be updated

### ISSUE THREAD

**Issue by cameronweibel** [Cognigy/Cognigy-CLI#10]
I just installed the cli with:
`npm install -g @cognigy/cognigy-cli`

Documentation:
![image](https://user-images.githubusercontent.com/8155129/115959723-e7f9d580-a50d-11eb-9eff-c22fa2872249.png)

Actual (note the <resourceType> needs to be added):
![image](https://user-images.githubusercontent.com/8155129/115959728-f34d0100-a50d-11eb-9120-15032ccd8b00.png)

Also, small capitalization error here:
![image](https://user-images.githubusercontent.com/8155129/115959777-298a8080-a50e-11eb-9135-e60fc29a119c.png)

**Comment by AlexTeusz** [comment]
Hey @cameronweibel ,

Thank you very much for this hint. We will update the documentation regarding your findings.

Thanks and Best
Alex

**Comment by AlexTeusz** [comment]
Done @cameronweibel , the README is adjusted based on your issue. https://github.com/Cognigy/Cognigy-CLI
