### ISSUE TITLE
cognigy execute --list should have optional command parameter

### ISSUE THREAD

**Issue by DanelGorgan** [Cognigy/Cognigy-CLI#11]
Hello,
According to the https://support.cognigy.com/hc/en-us/articles/360019857240-Cognigy-Sessions-CLI-and-API tutorial, using `cognigy execute --list` should work but testing locally it resturns `error: missing required argument 'command'` since as specified in the docs, a command is required. 

Shouldn't the "command" parameter be optional (since I don't know which command to use)? Also, by specifying a random text as "command" parameter, the list works as expected showing all commands. Is this expected behaviour? Thanks.

LE: unrelated to this question, where can I find a list with all the commands available (ex: indexFlows)?

**Comment by XavierJordaMurria** [comment]
In the next version that parameter will be optional as you suggest, it is what makes more sense.
Regarding your question, if you write e.g. ```cognigy execute indexFlows --list``` it should return a list of all the available commands that you can use in the cognigy execute
