### ISSUE TITLE
Error on  cognigy clone

### ISSUE THREAD

**Issue by KingofGnome** [Cognigy/Cognigy-CLI#123]
`cognigy clone` fails trying to clone a project

Error:
```bash
 This will delete all agent data you have stored currently locally. Do you want to proceed? Yes
Starting to clone your Agent to disk. This can take several minutes...

 ████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 11% | ETA: 1s |1/100
 ...\v18.17.1\node_modules\@cognigy\cognigy-cli\build\utils\indexAll2
            items: [...firstResponse.items],
                                     ^

TypeError: firstResponse.items is not iterable
    at indexAllFn (...\v18.17.1\node_modules\@cognigy\cognigy-cli\build\utils\indexAll.js:12:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async cloneEndpoints (...\v18.17.1\node_modules\@cognigy\cognigy-cli\build\lib\endpoints.js:44:23)
    at async Promise.all (index 1)
    at async clone (...\v18.17.1\node_modules\@cognigy\cognigy-cli\build\commands\clone.js:57:13)
    at async Command.<anonymous> (...\v18.17.1\node_modules\@cognigy\cognigy-cli\build\program\program.js:40:33)

Node.js v18.17.1
```

Also tested on Node 16 & 14, same issue.
Error is also unrelated to specific projects, as im unable to clone even an empty a freshly created project.

Tested with a fresh install of @cognigy-cli.
Also tested by cloning and building develop-branch: same error.

Any ideas?

**Comment by XavierJordaMurria** [comment]
Hi,
are you using the latest cognigyCLI version? 
if you run "cognigy --version" you should have 1.4.0

if so, could you please share your config.json file? no need to see the apikey, just the rest

**Comment by KingofGnome** [comment]
Hi, 
thanks for the fast response :)

config.json looks like this:
```
{
    "name": "xAppsDemo",
    "apiKey": "07...",
    "agent": "64e5c34894b384a758ac1934",
    "baseUrl": "https://arag-v4.cognigy.cloud/",
    "agentDir": "./agent",
    "filePath": "./config.json",
    "playbookTimeoutSeconds": "10"
}
```
cognigy --version is 1.4.0

**Comment by XavierJordaMurria** [comment]
the config file looks okay to me, the only thing it may cause an issue in the config.json file could be your last  "/" in the baseUrl, please try to remove it and test again.

how did you install the CLI?
I am trying to install the package globally and doing the whole setup from scratch and also building the binary from the repository, but I am able to clone a project with no problem.
you are saying this happens with a completely empty brand-new project too, right?

**Comment by KingofGnome** [comment]
Removing the / from the baseUrl had no effect.

Tried everything (once more) from scratch (including npm uninstall -g @cognigy/cognigy-cli)

My steps:
npm install -g @cognigy/cognigy-cli 
cognigy init
-> provide data directly or change config.json later
cognigy clone

same type-error:
TypeError: firstResponse.items is not iterable

Running on windows, Node.js v18.17.1, also tried with elevated(admin) terminal.

Also tried with projects on https://app.cognigy.ai, same result.

But if it works for you...i'll try with another computer later on, lets see.

**Comment by XavierJordaMurria** [comment]
right, I think I may know the issue. I did not see in your our environment but now that you mention the cognigy app environment I've spotted it.

the baseUrl has to be the API one, not the app one.
for the cognigy app environment try the following baseUrl: https://api-app.cognigy.ai/

**Comment by KingofGnome** [comment]
OMG, stupid me.
Yes that was the issue, thanks alot 👍👍👍
