### ISSUE TITLE
UnhandledPromiseRejection: [...] The promise rejected with the reason "Timeout"

### ISSUE THREAD

**Issue by tgbv** [Cognigy/Cognigy-CLI#130]
I received the below error after executing the following command:
```bash
cognigy train flow "flow_name"
```

```bash
Training intents for locale DE ... \node:internal/process/promises:288
triggerUncaughtException(err, true /* fromPromise */);
^
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Timeout".] {
code: 'ERR_UNHANDLED_REJECTION'
}
```

**A.** [The default timeout of 10 seconds](https://github.com/Cognigy/Cognigy-CLI/blob/develop/src/lib/flows.ts#L389) is very small. For one flow locale with many intents Cognigy NLU needs more time to build them. I believe it should be raised to at least 5 minutes.

**B.** The bigger problem is that function [src/utils/checks.checkTask](https://github.com/Cognigy/Cognigy-CLI/blob/develop/src/utils/checks.ts#L83) is not optimal. The interval in which CLI pools Cognigy API for task status is directly dependent on the timeout value. That means if I set the timeout value to 10 minutes, a flow with 0 intents will block the CLI process at least two minutes - [reference](https://github.com/Cognigy/Cognigy-CLI/blob/develop/src/utils/checks.ts#L97). Another issue with it is that it limits the nr of pooling trials to 5, also constrained by the timeout value.

**Comment by XavierJordaMurria** [comment]
Hi,
yes, you are right, that would need to be refactored.
Maybe you could create a feature request so we could get some time to work on this.
