### ISSUE TITLE
Version 1.5.0 still reports itself as 1.4.0 when running `cognigy --version`

### ISSUE THREAD

**Issue by dlukes** [Cognigy/Cognigy-CLI#161]
I think this line of code needs to be updated:

https://github.com/Cognigy/Cognigy-CLI/blob/f996a3b5ef415a9a2f57a5f8838434a26e3be5f3/src/program/program.ts#L31

**Comment by XavierJordaMurria** [comment]
thanks for reporting this.
I've just fixed this, it will get out in the next release
