### ISSUE TITLE
Intents-Array is unsorted and randomized each pull

### ISSUE THREAD

**Issue by KingofGnome** [Cognigy/Cognigy-CLI#33]
The intents.json-file in each flow, containing an array with each intent as json, stores the intents in **randomized order** (completely changing the file each clone/pull).
This does not happen to any other file/array, like in the chats.json.

Theres no reason for that, especially when the intents in cognigy-ui are shown in alphabetical order.

This could be fixed by sorting the intents by name in the [flow.js](https://github.com/Cognigy/Cognigy-CLI/blob/develop/src/lib/flows.ts) with something like this:

        const flowIntents = await CognigyClient.exportIntents({
            flowId: flow._id,
            localeId: locale._id,
            format: 'json',
            type: null
        });

        flowIntents.sort((a, b) => +(a.name > b.name) || -(a.name < b.name));

        fs.writeFileSync(localeDir + "/intents.json", JSON.stringify(flowIntents, undefined, 4));

However its probably better to find out why CognigyClient.exportIntents shuffles around the intents every pull and fix it there?

Motivation:
Randomized intent-files are a problem, as we're trying to create changelogs for botprojects using cognigy-cli+git and git can't handle the changes in intents if they're randomized each pull.

**Comment by petersenj** [comment]
I just created a pull request that concerns this issue - although I went the route of your suggestion and added sorting to intents, flow config, lexicon csv and endpoints config https://github.com/Cognigy/Cognigy-CLI/pull/39

**Comment by petersenj** [comment]
I now added pull request #40 that sorts lexicon data - slots and synonyms - as well :)
