### ISSUE TITLE
Missing configuration in environment variables or config.json

### ISSUE THREAD

**Issue by HichamLaaboudi** [Cognigy/Cognigy-CLI#84]
playbookTimeoutSeconds is not being set as an environment variable or in config.json, causing the following error when using cognigy clone:  Missing configuration in environment variables or config.json . When you set playbookTimeoutSeconds manually, the command can be used. However, [it is not stated in the docs that this is needed](https://support.cognigy.com/hc/en-us/articles/360016836580#install-cognigy-cli-0-0). I expected cognigy init to set this variable for me. 

Installed Cognigy CLI globally. 

Using MacOS 13.2.1

**Comment by XavierJordaMurria** [comment]
I am closing this issue, as it has been addressed already. right now it is in the develop branch and it will be released in a few days
